### ISSUE TITLE
port busy after closed

### ISSUE THREAD

**Issue by trlsmax** [wjwwood/serial#241] opened 2021-04-06 00:54 UTC
Hi, thanks for the great job on this lib.
I have a USB2Serial board, and other app can use the same serial port only if I close current app, close the port in current app can't help.
Is this a bug? 
I work on MacOS.

**Comment by wjwwood** [comment] 2021-06-10 22:22
Sorry, I'm not sure I understand the question. I believe only one application can use a port at a time, so it makes sense you have to close your application for another application to use it. Maybe you can clarify and ideally give steps to reproduce your issue.

I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Closed by wjwwood** 2021-06-10 22:22 UTC
