### ISSUE TITLE
Custom baudrate(100000) on Linux

### ISSUE THREAD

**Issue by QiayuanLiao** [wjwwood/serial#234] opened 2020-11-16 07:01 UTC
Baudrate was set to 100000 for dbus remote controller, and I couldn't open serial.
```
IO Exception (2): No such file or directory, file /xxxxx/impl/unix.cc, line115

````
I have already tested the port using `minicom` and it works well.

**Comment by wjwwood** [comment] 2021-06-10 22:34
That error is surprising to me, if the issue is baudrate, because it looks like the file for the device was wrong (maybe a typo?). Anyway without being able to reproduce it, I can't probably fix this. I appreciate you reporting it, maybe others will run into the same thing and comment here, but for now I will close it.

**Closed by wjwwood** 2021-06-10 22:34 UTC
