### ISSUE TITLE
Issue running Serial under root in Raspberry PI

### ISSUE THREAD

**Issue by xianrecords2015** [wjwwood/serial#227] opened 2020-08-13 07:06 UTC
I am having a strange issue. When I run my compiled c++ program under my user, the serial communication works fine.

But when I include the program in a rc.local or if I run the program under sudo (root), then the serial communication no longer works.

I am running on a Raspberry PI 4, Raspian.

**Comment by wjwwood** [comment] 2021-06-10 22:36
I don't know why that would be an issue (especially as root), but if it were in fact running under a user and that user wasn't in the correct groups that might be the issue. I'm going to close this for now, since I cannot easily reproduce it.

**Closed by wjwwood** 2021-06-10 22:36 UTC
