### ISSUE TITLE
How to add the library to my code after "make install"

### ISSUE THREAD

**Issue by dottantgal** [wjwwood/serial#129] opened 2016-05-23 15:10 UTC
Hi, I wanna add the library to my own code, but I don't know how to include it in the Cmakelists file.
It gives me an error  "fatal error: serial/serial.h"
This is how my CMakeLists looks like

cmake_minimum_required(VERSION 2.8.3)
project(serial_sensor)
set (BINNAME serial_sensor)
set (SRCS1 ${SRCS1} src/serial_sensor.cpp)
find_package(catkin REQUIRED COMPONENTS
  roscpp
  rospy
  std_msgs
  tf
  message_generation
)
add_message_files(
  FILES
  Altitude.msg
  Heading.msg
  Pressure.msg
)
generate_messages(
   DEPENDENCIES
   std_msgs
)
catkin_package(
  LIBRARIES serial
  CATKIN_DEPENDS message_runtime
)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
include_directories(include ${catkin_INCLUDE_DIRS})
add_executable(serial_motors src/serial_motors.cpp)
target_link_libraries(serial_motors ${catkin_LIBRARIES})
add_executable (${BINNAME} ${SRCS1})
add_dependencies(${BINNAME} ${PROJECT_NAME}_generate_messages_cpp)
target_link_libraries(${BINNAME} ${catkin_LIBRARIES})

I ve followed the "how to" till the "make install" and this last command gives me

Install the project...
-- Install configuration: ""
-- Installing: /tmp/usr/local/_setup_util.py
-- Installing: /tmp/usr/local/env.sh
-- Installing: /tmp/usr/local/setup.bash
-- Installing: /tmp/usr/local/setup.sh
-- Installing: /tmp/usr/local/setup.zsh
-- Installing: /tmp/usr/local/.rosinstall
-- Installing: /tmp/usr/local/lib/pkgconfig/serial.pc
-- Installing: /tmp/usr/local/share/serial/cmake/serialConfig.cmake
-- Installing: /tmp/usr/local/share/serial/cmake/serialConfig-version.cmake
-- Installing: /tmp/usr/local/share/serial/package.xml
-- Installing: /tmp/usr/local/lib/libserial.so
-- Installing: /tmp/usr/local/include/serial/serial.h
-- Installing: /tmp/usr/local/include/serial/v8stdint.h

is it strange that it installs under the tmp folder?
Thank you

**Comment by wjwwood** [comment] 2016-05-23 17:32
duplicate of https://github.com/wjwwood/serial/issues/128

**Closed by wjwwood** 2016-05-23 17:32 UTC
